[build]
  publish = "site"
  command = "./build-netlify-v2.sh"
  #command = "./build_script_versioned-v5.sh"
  #command = "./build-netlify.sh"
  # command = "pip install -r requirements.txt && git submodule update --init --recursive && mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.11"

